
[font]
size = 13

[font.normal]
# family = "JetBrainsMono Nerd Font Propo"
# family = "Consolas Nerd Font"
family = "SauceCodePro Nerd Font Mono"
style = "Medium"

[window]
opacity = 1.0

[window.padding]
x = 8
y = 8

[selection]
save_to_clipboard = true

[general]
import = [
    "~/.cache/wal/colors-alacritty.toml"
]

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Shift | Super"
