
[font]
size = 12.5

[font.normal]
# family = "JetBrainsMono Nerd Font Propo"
family = "Maple Mono"
# family = "Source Code Pro Medium"

[window]
opacity = 1.0

[window.padding]
x = 8
y = 8

[selection]
save_to_clipboard = true

[general]
import = [
    "~/.cache/wal/colors-alacritty.toml"
]

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Shift | Super"
