include ./dank-theme.conf
font_family JetBrainsMono Nerd Font Propo
font_size 14
allow_remote_control yes
window_padding_width 6

map super+shift+enter new_os_window_with_cwd
map ctrl+shift+enter launch --cwd=current


# BEGIN_KITTY_THEME
# Catppuccin Kitty Mocha
include current-theme.conf
# END_KITTY_THEME
