set background=dark
if exists('g:colors_name')
hi clear
if exists('syntax_on')
syntax reset
endif
endif
let g:colors_name = 'lushwal'
highlight Normal guifg=#EDF0F2 guibg=#253137 guisp=NONE blend=NONE gui=NONE
highlight! link User Normal
highlight Bold guifg=#EDF0F2 guibg=#253137 guisp=NONE blend=NONE gui=bold
highlight Boolean guifg=#FFAC05 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Character guifg=#FF9900 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight ColorColumn guifg=#5B7480 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Comment guifg=#D0D9DD guibg=NONE guisp=NONE blend=NONE gui=italic
highlight Conceal guifg=#36464E guibg=#253137 guisp=NONE blend=NONE gui=NONE
highlight! link Whitespace Conceal
highlight Conditional guifg=#A76DFE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Constant guifg=#FFAC05 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Cursor guifg=#253137 guibg=#EDF0F2 guisp=NONE blend=NONE gui=NONE
highlight CursorColumn guifg=#5B7480 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight CursorLine guifg=#36464E guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight CursorLineNr guifg=#D0D9DD guibg=#253137 guisp=NONE blend=NONE gui=NONE
highlight Debug guifg=#FF9900 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Define guifg=#A76DFE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Delimiter guifg=#F5800A guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiagnosticError guifg=#FF9900 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiagnosticHint guifg=#009485 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiagnosticInfo guifg=#02A6F2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiagnosticUnderlineError guifg=#FF9900 guibg=NONE guisp=#FF9900 blend=NONE gui=underline
highlight DiagnosticUnderlineHint guifg=#009485 guibg=NONE guisp=#009485 blend=NONE gui=underline
highlight DiagnosticUnderlineInfo guifg=#02A6F2 guibg=NONE guisp=#02A6F2 blend=NONE gui=underline
highlight DiagnosticUnderlineWarn guifg=#FFC105 guibg=NONE guisp=#FFC105 blend=NONE gui=underline
highlight DiagnosticWarn guifg=#FFC105 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiffAdd guifg=#8BC34B guibg=#36464E guisp=NONE blend=NONE gui=bold
highlight! link DiffAdded DiffAdd
highlight DiffChange guifg=#94A9B3 guibg=#36464E guisp=NONE blend=NONE gui=NONE
highlight DiffDelete guifg=#FF9900 guibg=#36464E guisp=NONE blend=NONE gui=bold
highlight! link DiffRemoved DiffDelete
highlight! link diffRemoved DiffDelete
highlight DiffFile guifg=#FF9900 guibg=#253137 guisp=NONE blend=NONE gui=NONE
highlight DiffLine guifg=#02A6F2 guibg=#253137 guisp=NONE blend=NONE gui=NONE
highlight DiffNewFile guifg=#8BC34B guibg=#253137 guisp=NONE blend=NONE gui=NONE
highlight DiffText guifg=#02A6F2 guibg=#36464E guisp=NONE blend=NONE gui=NONE
highlight Directory guifg=#02A6F2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight EndOfBuffer guifg=#EDF0F2 guibg=#253137 guisp=NONE blend=NONE gui=NONE
highlight Error guifg=#FF9900 guibg=#D0D9DD guisp=NONE blend=NONE gui=NONE
highlight ErrorMsg guifg=#FF9900 guibg=#253137 guisp=NONE blend=NONE gui=NONE
highlight Exception guifg=#FF9900 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Float guifg=#FFAC05 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight FoldColumn guifg=#02A6F2 guibg=#253137 guisp=NONE blend=NONE gui=NONE
highlight Folded guifg=#D0D9DD guibg=#36464E guisp=NONE blend=NONE gui=italic
highlight Function guifg=#02A6F2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Identifier guifg=#009485 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight IncSearch guifg=#36464E guibg=#FFAC05 guisp=NONE blend=NONE gui=NONE
highlight Include guifg=#02A6F2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Italic guifg=#EDF0F2 guibg=#253137 guisp=NONE blend=NONE gui=italic
highlight Keyword guifg=#A76DFE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Label guifg=#FFC105 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight LineNr guifg=#94A9B3 guibg=#253137 guisp=NONE blend=NONE gui=NONE
highlight Macro guifg=#FF9900 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MatchParen guifg=#EDF0F2 guibg=#94A9B3 guisp=NONE blend=NONE gui=NONE
highlight MiniCompletionActiveParameter guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniCursorword guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=underline
highlight! link MiniCursorwordCurrent MiniCursorword
highlight MiniIndentscopePrefix guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=nocombine
highlight MiniIndentscopeSymbol guifg=#36464E guibg=#253137 guisp=NONE blend=NONE gui=NONE
highlight MiniJump guifg=#02A6F2 guibg=NONE guisp=#94A9B3 blend=NONE gui=underline
highlight MiniJump2dSpot guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=undercurl
highlight MiniStarterCurrent guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStarterFooter guifg=#02A6F2 guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniStarterHeader guifg=#02A6F2 guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniStarterInactive guifg=#D0D9DD guibg=NONE guisp=NONE blend=NONE gui=italic
highlight MiniStarterItem guifg=#EDF0F2 guibg=#253137 guisp=NONE blend=NONE gui=NONE
highlight MiniStarterItemBullet guifg=#F5800A guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStarterItemPrefix guifg=#FF9900 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStarterQuery guifg=#8BC34B guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStarterSection guifg=#F5800A guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineDevinfo guifg=#D0D9DD guibg=#36464E guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineFileinfo guifg=#D0D9DD guibg=#36464E guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineFilename guifg=#FFC105 guibg=#36464E guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineInactive guifg=#5B7480 guibg=#36464E guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeCommand guifg=#253137 guibg=#009485 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeInsert guifg=#253137 guibg=#02A6F2 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeNormal guifg=#253137 guibg=#8BC34B guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeOther guifg=#253137 guibg=#A76DFE guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeReplace guifg=#253137 guibg=#FF9900 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeVisual guifg=#253137 guibg=#FFAC05 guisp=NONE blend=NONE gui=NONE
highlight MiniSurround guifg=#36464E guibg=#FFAC05 guisp=NONE blend=NONE gui=NONE
highlight MiniTablineCurrent guifg=#94A9B3 guibg=#36464E guisp=NONE blend=NONE gui=NONE
highlight MiniTablineFill guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniTablineHidden guifg=#8BC34B guibg=#36464E guisp=NONE blend=NONE gui=NONE
highlight MiniTablineModifiedCurrent guifg=#D0D9DD guibg=#36464E guisp=NONE blend=NONE gui=NONE
highlight MiniTablineModifiedHidden guifg=#5B7480 guibg=#36464E guisp=NONE blend=NONE gui=NONE
highlight MiniTablineModifiedVisible guifg=#D0D9DD guibg=#36464E guisp=NONE blend=NONE gui=NONE
highlight MiniTablineVisible guifg=#94A9B3 guibg=#36464E guisp=NONE blend=NONE gui=NONE
highlight MiniTestEmphasis guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniTestFail guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniTestPass guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniTrailspace guifg=#FF9900 guibg=#D0D9DD guisp=NONE blend=NONE gui=NONE
highlight ModeMsg guifg=#8BC34B guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MoreMsg guifg=#8BC34B guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight NonText guifg=#94A9B3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Number guifg=#FFAC05 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Operator guifg=#EDF0F2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight PMenu guifg=#D0D9DD guibg=#36464E guisp=NONE blend=NONE gui=NONE
highlight PMenuSel guifg=#EDF0F2 guibg=#02A6F2 guisp=NONE blend=NONE gui=NONE
highlight PmenuSbar guifg=#5B7480 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight PmenuThumb guifg=#EDF0F2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight PreProc guifg=#FFC105 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Question guifg=#02A6F2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Repeat guifg=#FFC105 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Search guifg=#94A9B3 guibg=#FFC105 guisp=NONE blend=NONE gui=NONE
highlight! link MiniTablineTabpagesection Search
highlight SignColumn guifg=#5B7480 guibg=#253137 guisp=NONE blend=NONE gui=NONE
highlight Special guifg=#009485 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight SpecialChar guifg=#F5800A guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight SpecialKey guifg=#94A9B3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight SpellBad guifg=#FF9900 guibg=NONE guisp=#FF9900 blend=NONE gui=underline
highlight SpellCap guifg=#FFC105 guibg=NONE guisp=#FFC105 blend=NONE gui=underline
highlight SpellLocal guifg=#009485 guibg=NONE guisp=#009485 blend=NONE gui=underline
highlight SpellRare guifg=#A76DFE guibg=NONE guisp=#A76DFE blend=NONE gui=underline
highlight Statement guifg=#FF9900 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight StatusLine guifg=#D0D9DD guibg=#36464E guisp=NONE blend=NONE gui=NONE
highlight StatusLineNC guifg=#5B7480 guibg=#36464E guisp=NONE blend=NONE gui=NONE
highlight StatusLineTerm guifg=#8BC34B guibg=#8BC34B guisp=NONE blend=NONE gui=NONE
highlight StatusLineTermNC guifg=#FFC105 guibg=#36464E guisp=NONE blend=NONE gui=NONE
highlight StorageClass guifg=#FFC105 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight String guifg=#8BC34B guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Structure guifg=#A76DFE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight TabLine guifg=#94A9B3 guibg=#36464E guisp=NONE blend=NONE gui=NONE
highlight TabLineFill guifg=#94A9B3 guibg=#36464E guisp=NONE blend=NONE gui=NONE
highlight TabLineSel guifg=#8BC34B guibg=#36464E guisp=NONE blend=NONE gui=NONE
highlight Tag guifg=#FFC105 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Title guifg=#02A6F2 guibg=NONE guisp=NONE blend=NONE gui=bold
highlight Todo guifg=#FFC105 guibg=#36464E guisp=NONE blend=NONE gui=NONE
highlight TooLong guifg=#FF9900 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Type guifg=#FFC105 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Typedef guifg=#FFC105 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Underlined guifg=#FF9900 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight VertSplit guifg=#D0D9DD guibg=#253137 guisp=NONE blend=NONE gui=NONE
highlight! link WinSeparator VertSplit
highlight Visual guifg=#253137 guibg=#5B7480 guisp=NONE blend=NONE gui=NONE
highlight VisualNOS guifg=#FF9900 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight WarningMsg guifg=#FF9900 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight WildMenu guifg=#EDF0F2 guibg=#02A6F2 guisp=NONE blend=NONE gui=NONE
highlight WinBar guifg=#D0D9DD guibg=#253137 guisp=NONE blend=NONE gui=NONE
highlight WinBarNC guifg=#5B7480 guibg=#253137 guisp=NONE blend=NONE gui=NONE
highlight gitCommitOverflow guifg=#FF9900 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight gitCommitSummary guifg=#8BC34B guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight helpCommand guifg=#FFC105 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight helpExample guifg=#FFC105 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @attribute guifg=#02A6F2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @boolean guifg=#02A6F2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @character guifg=#FFC105 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @character.special guifg=#F5800A guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @comment guifg=#D0D9DD guibg=NONE guisp=NONE blend=NONE gui=italic
highlight @conditional guifg=#FF9900 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @constant guifg=#FF9900 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @constant.builtin guifg=#FF9900 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @constant.macro guifg=#FF9900 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @constructor guifg=#EDF0F2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @debug guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @define guifg=#A76DFE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @exception guifg=#FF9900 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @field guifg=#8BC34B guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @float guifg=#02A6F2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @function guifg=#02A6F2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @function.builtin guifg=#FF9900 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @function.macro guifg=#FF9900 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @include guifg=#009485 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @keyword guifg=#A76DFE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @keyword.function guifg=#009485 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @keyword.operator guifg=#A76DFE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @label guifg=#009485 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @method guifg=#02A6F2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @namespace guifg=#02A6F2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @none guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @number guifg=#02A6F2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @operator guifg=#EDF0F2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @parameter guifg=#FFC105 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @preproc guifg=#FFC105 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @property guifg=#FFC105 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @punctuation.bracket guifg=#EDF0F2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @punctuation.delimiter guifg=#EDF0F2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @punctuation.special guifg=#009485 guibg=NONE guisp=NONE blend=NONE gui=bold
highlight @repeat guifg=#FF9900 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @storageclass guifg=#FFC105 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @string guifg=#02A6F2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @string.escape guifg=#8BC34B guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @string.regex guifg=#8BC34B guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @string.special guifg=#F5800A guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @symbol guifg=#009485 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @tag guifg=#FFC105 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @tag.attribute guifg=#009485 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @tag.delimiter guifg=#009485 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text guifg=#8BC34B guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.bold guifg=#FFC105 guibg=NONE guisp=NONE blend=NONE gui=bold
highlight @text.danger guifg=#FF9900 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.diff.add guifg=#8BC34B guibg=#36464E guisp=NONE blend=NONE gui=bold
highlight @text.diff.delete guifg=#FF9900 guibg=#36464E guisp=NONE blend=NONE gui=bold
highlight @text.emphasis guifg=#A76DFE guibg=NONE guisp=NONE blend=NONE gui=italic
highlight @text.environment guifg=#FF9900 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.environment.name guifg=#FFC105 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.literal guifg=#8BC34B guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.math guifg=#009485 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.note guifg=#009485 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.reference guifg=#FF9900 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.strike guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=strikethrough
highlight @text.title guifg=#02A6F2 guibg=NONE guisp=NONE blend=NONE gui=bold
highlight @text.todo guifg=#FFC105 guibg=#36464E guisp=NONE blend=NONE gui=NONE
highlight @text.underline guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=underline
highlight @text.uri guifg=NONE guibg=#36464E guisp=NONE blend=NONE gui=underline
highlight @type guifg=#02A6F2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @type.builtin guifg=#02A6F2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @type.definition guifg=#FFC105 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @variable guifg=#FFC105 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @variable.builtin guifg=#FF9900 guibg=NONE guisp=NONE blend=NONE gui=NONE
