source = /home/pateraki/.cache/wal/colors-hyprland.conf

background {
    path = /home/pateraki/.wallpaper
    blur_passes = 3
}

#rectangle
shape {
    monitor =
    size = 600, 400
    rounding = 4
    border_size = 2
    border_color = 0xff$color8
    color = 0xff$background
    position = 0, 0
    halign = center
    valign = center
}

# user profile pic
# shape {
#     monitor =
#     size = 80, 80
#     rounding = -1
#     color = 0xff$foreground
#     position = 0, 120 
#     halign = center
#     valign = center
# }
image {
    monitor =
    path = /var/lib/AccountsService/icons/$USER
    border_size = 2
    border_color = 0xff$foreground
    halign = center
    valign = center
    position = 0, 120
    size = 96
}

# user name (desc)
label {
    monitor = 
    text = $DESC
    text_align = center
    font_family = Fira Sans 
    color = 0xff$color4
    font_size = 18
    halign = center
    valign = center
    position = 0, 50 
}

# time
label {
    monitor = 
    text = cmd[update:5000] echo $(date '+%H:%M')
    text_align = center
    font_family = Fira Sans Medium
    color = 0xff$foreground
    font_size = 32
    halign = center
    valign = center
    position = 0, 0 
}

# date
label {
    monitor = 
    text = cmd[update:10000] echo $(date '+%A, %d %B %Y')
    text_align = center
    font_family = Fira Sans
    color = 0xff$foreground
    font_size = 20
    halign = center
    valign = center
    position = 0, -40
}

# password input
input-field {
    monitor =
    size = 300, 30
    outline_thickness = 2
    dots_size = 0.3333
    
    outer_color = 0xff$color7
    inner_color = 0xff$color0
    font_color = 0xff$color15
    check_color = 0xff$color4
    fail_color = 0xff$color1
    capslock_color = 0xff$color3

    font_family = Fira Sans
    fade_timeout = 3000

    position = 0, -120
    halign = center
    valign = center
}

label {
    monitor = 
    text = Layout: $LAYOUT
    color = 0xff$color7
    font_family = Fira Sans
    font_size = 12
    halign = center
    valign = center
    position = 0, -160
}

