# QT theme settings
env = QT_AUTOSCREEN_SCALE_FACTOR,1
env = QT_QPA_PLATFORMTHEME,qt5ct

# GTK: Use wayland if available. If not: try x11, then any other GDK backend.
env = GDK_BACKEND,wayland,x11,*
# Qt: Use wayland if available, fall back to x11 if not.
env = QT_QPA_PLATFORM,wayland;xcb
# Run SDL2 applications on Wayland. Remove or set to x11 if games that provide older versions of SDL cause compatibility issues
env = SDL_VIDEODRIVER,wayland
# Clutter package already has wayland enabled, this variable will force Clutter applications to try and use the Wayland backend
env = CLUTTER_BACKEND,wayland

# xdg desktop portal settings
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
