source = /home/pateraki/.cache/wal/colors-hyprland.conf

background {
    path = /home/pateraki/ownCloud/Wallpapers/iliana_window.png
    blur_passes = 4
}

# user profile pic
image {
    monitor =
    path = /var/lib/AccountsService/icons/$USER
    border_size = 4
    border_color = 0xff$background
    halign = center
    valign = center
    position = 0, 200
    size = 80
}

# user name (desc)
label {
    monitor = 
    text = $DESC
    text_align = center
    font_family = Aptos
    color = 0xff$color4
    font_size = 24
    halign = center
    valign = center
    position = 0, 120
}

# time
label {
    monitor = 
    text = cmd[update:5000] echo $(date '+%H:%M')
    text_align = center
    font_family = Aptos
    color = 0xff$foreground
    font_size = 48 
    halign = center
    valign = center
    position = 0, 0
}

# date
label {
    monitor = 
    text = cmd[update:10000] echo $(date '+%A, %d %B %Y')
    text_align = center
    font_family = Aptos
    color = 0xff$foreground
    font_size = 18
    halign = center
    valign = center
    position = 0, -50 
}

# password input
input-field {
    monitor =
    size = 350, 50
    outline_thickness = 4
    dots_size = 0.3333
    
    outer_color = 0xff$color0
    inner_color = 0xff$color7
    font_color = 0xff$color0
    check_color = 0xff$color4
    fail_color = 0xff$color1
    capslock_color = 0xff$color3

    fade_timeout = 3000

    position = 0, -200
    halign = center
    valign = center
}

label {
    monitor = 
    text = Layout: $LAYOUT
    text-align = center
    color = 0xff$color8
    font_family = Aptos
    font_size = 14
    halign = center
    valign = center
    position = 0, -480
}

