ipc = on
preload = ~/ownCloud/Wallpapers/iliana_window.png
preload = ~/ownCloud/Wallpapers/OvLfalu.png
preload = ~/ownCloud/Wallpapers/wenniel-lun-239353.jpg
preload = ~/ownCloud/Wallpapers/dTpzJdK.jpg

wallpaper = ~/ownCloud/Wallpapers/dTpzJdK.jpg
# wallpaper = ,~/ownCloud/Wallpapers/iliana_window.png
